name: clients
description: Flyer Eats Clients

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sliding_up_panel: ^1.0.2
  flutter_svg: ^0.18.0
  after_layout: ^1.0.7+2
  font_awesome_flutter: ^8.8.1
  shimmer: ^1.1.1
  cached_network_image: ^2.2.0+1
  custom_switch: ^0.0.1
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  dotted_border: ^1.0.5
  image_picker: ^0.6.6+4
  sqflite: ^1.3.0+1
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2
  location: ^3.0.2
  google_map_location_picker: ^3.3.1
  flutter_spinkit: ^4.1.2+1
  pin_code_fields: ^3.0.1
  shared_preferences: ^0.5.7+3
  smooth_star_rating: 1.1.1
  package_info: ^0.4.1
  device_info: ^0.4.2+4
  dio: ^3.0.9
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_facebook_login: 3.0.0
  razorpay_flutter: ^1.2.1
  google_fonts: ^1.1.0
  scratcher: 1.4.0
  modal_bottom_sheet: ^0.2.0
  mask_text_input_formatter: ^1.0.7
  firebase_messaging: ^6.0.9
  flutter_local_notifications: ^1.4.4+2
  share: ^0.6.4+3
  video_player: ^0.10.11+2
  sms_autofill: ^1.2.3
  url_launcher: ^5.5.0
  youtube_player_flutter: ^6.0.3
  stripe_payment: ^1.0.7
  fluttertoast: ^7.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/banner1.jpg
    - assets/banner2.png
    - assets/meat.svg
    - assets/restaurants.svg
    - assets/vegfruits.svg
    - assets/groceries.svg
    - assets/drawer.svg
    - assets/location.svg
    - assets/1.svg
    - assets/2.svg
    - assets/3.svg
    - assets/4.svg
    - assets/back.svg
    - assets/rupee.svg
    - assets/grid.svg
    - assets/list.svg
    - assets/box_circle.svg
    - assets/box_circle_red.svg
    - assets/allrestaurant.png
    - assets/pickup.png
    - assets/delivery.svg
    - assets/selfpickup.svg
    - assets/locationpick.svg
    - assets/discount.svg
    - assets/attachment.svg
    - assets/distance.svg
    - assets/home_icon.svg
    - assets/other_address.svg
    - assets/check_icon.svg
    - assets/avatar.png
    - assets/additems.svg
    - assets/remove.svg
    - assets/time.svg
    - assets/discount2.svg
    - assets/search.svg
    - assets/account.svg
    - assets/check.svg
    - assets/wallet.svg
    - assets/currentloc.svg
    - assets/facebook.svg
    - assets/gmail.svg
    - assets/flyereatslogo.png
    - assets/india_flag.svg
    - assets/singapore_flag.svg
    - assets/onlinepayment.svg
    - assets/cod.svg
    - assets/coming soon.svg
    - assets/coming soon 2.svg
    - assets/ordersuccess icon.png
    - assets/order success icon 2.svg
    - assets/no food.svg
    - assets/no merchant.svg
    - assets/add review icon.svg
    - assets/delivered signature.svg
    - assets/delivered signature.png
    - assets/cancelled icon.svg
    - assets/separator icon.svg
    - assets/delivered icon.svg
    - assets/on the way icon.svg
    - assets/food preparing icon.svg
    - assets/order placed icon.svg
    - assets/no available items cart.svg
    - assets/no available items cart.jpg
    - assets/dropdown home.svg
    - assets/in process icon.svg
    - assets/calendar.svg
    - assets/clock.svg
    - assets/pending icon.svg
    - assets/sg dollar.svg
    - assets/no offers available icon.svg
    - assets/office address.svg
    - assets/others address.svg
    - assets/home address.svg
    - assets/flyereatslogo2.png
    - assets/scratch card.png
    - assets/warnings.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
